<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page-setting[
<!ELEMENT page-setting (css-files?,jscript-files?,pages?)>
<!ELEMENT css-files (css-file+)>
<!ELEMENT jscript-files (jscript-file+)>
<!ELEMENT pages (page+)>
<!ELEMENT page (enterkey-orders?)>
<!ELEMENT enterkey-orders (enterkey-order+)>
<!ATTLIST css-file
  path CDATA #REQUIRED>
<!ATTLIST jscript-file
  path CDATA #REQUIRED>
<!ATTLIST page
  path CDATA #REQUIRED
  resource-key CDATA #REQUIRED>
<!ATTLIST enterkey-order
  order NMTOKEN #REQUIRED
  control-id CDATA #REQUIRED>
]>
<page-setting>
  <css-files>
    <css-file path="/css/common.css" />
    <css-file path="/css/listcell.css" />
    <css-file path="/css/user.css" />
  </css-files>
  <jscript-files>
    <jscript-file path="/jscript/user.js" />
  </jscript-files>
  <pages>
    <page path="/login/Login" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/login/LoginSuccess" resource-key="">
      <enterkey-orders />
      <regulartransmission time="0" />
    </page>
    <page path="/login/LoginCheck" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/login/LoginUserList" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/login/LoginUserMaintenance" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/progress" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/Error" resource-key="">
      <enterkey-orders />
    </page>
    <page path="/shipping/shippinginspection/ShippingInspection" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_ConsignorCode" />
        <enterkey-order order="4" control-id="txt_ShippingPlanDate" />
        <enterkey-order order="5" control-id="txt_CustomerCode" />
        <enterkey-order order="6" control-id="txt_ItemCode" />
        <enterkey-order order="7" control-id="rdo_TicTkt" />
        <enterkey-order order="8" control-id="chk_CommonUse" />
        <enterkey-order order="9" control-id="lst_SShpIsp" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingworkmaintenance/ShippingWorkMaintenance" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_ConsignorCode" />
        <enterkey-order order="4" control-id="pul_WorkStatus" />
        <enterkey-order order="5" control-id="txt_ShippingPlanDate" />
        <enterkey-order order="6" control-id="txt_CustomerCode" />
        <enterkey-order order="7" control-id="txt_StartTicketNo" />
        <enterkey-order order="8" control-id="txt_EndTicketNo" />
        <enterkey-order order="9" control-id="txt_ItemCode" />
        <enterkey-order order="10" control-id="lst_SShpWkMtn" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingworkinginquiry/ShippingWorkingInquiry" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_ShippingPlanDate" />
        <enterkey-order order="2" control-id="txt_ConsignorCode" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplanregist/ShippingPlanRegist" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_ConsignorCode" />
        <enterkey-order order="4" control-id="txt_ConsignorName" />
        <enterkey-order order="5" control-id="txt_ShippingPlanDate" />
        <enterkey-order order="6" control-id="txt_CustomerCode" />
        <enterkey-order order="7" control-id="txt_CustomerName" />
        <enterkey-order order="8" control-id="txt_TicketNo" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplanregist/ShippingPlanRegist2" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LineNo" />
        <enterkey-order order="2" control-id="txt_ItemCode" />
        <enterkey-order order="3" control-id="txt_ItemName" />
        <enterkey-order order="4" control-id="txt_CaseEntering" />
        <enterkey-order order="5" control-id="txt_PlanCaseQty" />
        <enterkey-order order="6" control-id="txt_CaseItf" />
        <enterkey-order order="7" control-id="txt_BundleEntering" />
        <enterkey-order order="8" control-id="txt_PlanPieceQty" />
        <enterkey-order order="9" control-id="txt_BundleItf" />
        <enterkey-order order="10" control-id="rdo_CrossDCFlagTC" />
        <enterkey-order order="11" control-id="txt_SupplierCode" />
        <enterkey-order order="12" control-id="txt_SupplierName" />
        <enterkey-order order="13" control-id="txt_InstockTicketNo" />
        <enterkey-order order="14" control-id="txt_InstkTktLineNo" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplanmodify/ShippingPlanModify" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_ConsignorCode" />
        <enterkey-order order="4" control-id="txt_ShippingPlanDate" />
        <enterkey-order order="5" control-id="txt_CustomerCode" />
        <enterkey-order order="6" control-id="txt_TicketNo" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplanmodify/ShippingPlanModify2" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LineNo" />
        <enterkey-order order="2" control-id="txt_ItemCode" />
        <enterkey-order order="3" control-id="txt_ItemName" />
        <enterkey-order order="4" control-id="txt_CaseEntering" />
        <enterkey-order order="5" control-id="txt_PlanCaseQty" />
        <enterkey-order order="6" control-id="txt_CaseItf" />
        <enterkey-order order="7" control-id="txt_BundleEntering" />
        <enterkey-order order="8" control-id="txt_PlanPieceQty" />
        <enterkey-order order="9" control-id="txt_BundleItf" />
        <enterkey-order order="10" control-id="rdo_CrossDCFlagTC" />
        <enterkey-order order="11" control-id="txt_SupplierCode" />
        <enterkey-order order="12" control-id="txt_SupplierName" />
        <enterkey-order order="13" control-id="txt_InstockTicketNo" />
        <enterkey-order order="14" control-id="txt_InstkTktLineNo" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplaninquiry/ShippingPlanInquiry" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ConsignorCode" />
        <enterkey-order order="2" control-id="txt_StrtShpPlanDate" />
        <enterkey-order order="3" control-id="txt_EdShpPlanDate" />
        <enterkey-order order="4" control-id="txt_CustomerCode" />
        <enterkey-order order="5" control-id="txt_StartTicketNo" />
        <enterkey-order order="6" control-id="txt_EndTicketNo" />
        <enterkey-order order="7" control-id="txt_ItemCode" />
        <enterkey-order order="8" control-id="pul_WorkStatusShipping" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingqtyinquiry/ShippingQtyInquiry" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ConsignorCode" />
        <enterkey-order order="2" control-id="txt_StartShippingDate" />
        <enterkey-order order="3" control-id="txt_EndShippingDate" />
        <enterkey-order order="4" control-id="txt_CustomerCode" />
        <enterkey-order order="5" control-id="txt_TicketNo" />
        <enterkey-order order="6" control-id="txt_ItemCode" />
        <enterkey-order order="7" control-id="rdo_SpdShpDate" />
        <enterkey-order order="8" control-id="rdo_TicTkt" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippinglist/ShippingList" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ConsignorCode" />
        <enterkey-order order="2" control-id="txt_StrtShpPlanDate" />
        <enterkey-order order="3" control-id="txt_EdShpPlanDate" />
        <enterkey-order order="4" control-id="txt_CustomerCode" />
        <enterkey-order order="5" control-id="txt_TicketNo" />
        <enterkey-order order="6" control-id="txt_ItemCode" />
        <enterkey-order order="7" control-id="pul_WorkStatus" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplanlist/ShippingPlanList" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ConsignorCode" />
        <enterkey-order order="2" control-id="txt_StrtShpPlanDate" />
        <enterkey-order order="3" control-id="txt_EdShpPlanDate" />
        <enterkey-order order="4" control-id="txt_CustomerCode" />
        <enterkey-order order="5" control-id="txt_TicketNo" />
        <enterkey-order order="6" control-id="txt_ItemCode" />
        <enterkey-order order="7" control-id="pul_WorkStatusShipping" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingqtylist/ShippingQtyList" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ConsignorCode" />
        <enterkey-order order="2" control-id="txt_StartShippingDate" />
        <enterkey-order order="3" control-id="txt_EndShippingDate" />
        <enterkey-order order="4" control-id="txt_CustomerCode" />
        <enterkey-order order="5" control-id="txt_TicketNo" />
        <enterkey-order order="6" control-id="txt_ItemCode" />
      </enterkey-orders>
    </page>
    <page path="/shipping/shippingplandelete/ShippingPlanDelete" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_ConsignorCode" />
        <enterkey-order order="4" control-id="txt_StrtShpPlanDate" />
        <enterkey-order order="5" control-id="txt_EdShpPlanDate" />
        <enterkey-order order="6" control-id="chk_CommonUse" />
        <enterkey-order order="7" control-id="lst_SShippingPlanDtaDlt" />
      </enterkey-orders>
    </page>
    <page path="/shipping/listbox/listshippingcustomer/ListShippingCustomer" resource-key="TLE-W0031">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingitem/ListShippingItem" resource-key="TLE-W0043">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingqtylist/ListShippingQtyList" resource-key="TLE-W0059">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingdate/ListShippingDate" resource-key="TLE-W0029">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingticket/ListShippingTicket" resource-key="TLE-W0047">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingplan/ListShippingPlan" resource-key="TLE-W0037">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingsupplier/ListShippingSupplier" resource-key="TLE-W0021">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippinglist/ListShippingList" resource-key="TLE-W0058">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingplanlist/ListShippingPlanList" resource-key="TLE-W0037">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingplandate/ListShippingPlanDate" resource-key="TLE-W0039">
      <enterkey-orders />
    </page>
    <page path="/shipping/listbox/listshippingconsignor/ListShippingConsignor" resource-key="TLE-W0012">
      <enterkey-orders />
    </page>
    <page path="/system/defineloaddatamenu/DefineLoadDataMenu" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="rdo_Plan_Instock" />
        <enterkey-order order="4" control-id="rdo_Plan_Storage" />
        <enterkey-order order="5" control-id="rdo_Plan_Retrieval" />
        <enterkey-order order="6" control-id="rdo_Plan_Picking" />
        <enterkey-order order="7" control-id="rdo_Plan_Shipping" />
      </enterkey-orders>
    </page>
    <page path="/system/defineloaddatamenu/DefineLoadDataMenuShipping" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ShpPlanDateReqPst" />
        <enterkey-order order="33" control-id="chk_CommonUseItemName" />
        <enterkey-order order="34" control-id="txt_ItemNmLen" />
        <enterkey-order order="35" control-id="txt_ItemNmPst" />
        <enterkey-order order="2" control-id="chk_CommonUseOrderDate" />
        <enterkey-order order="3" control-id="txt_OdrgDatePst" />
        <enterkey-order order="36" control-id="txt_ShpQtyPtlLenReq" />
        <enterkey-order order="37" control-id="txt_ShpQtyPtlPstReq" />
        <enterkey-order order="4" control-id="chk_CommonUseConsignorCode" />
        <enterkey-order order="5" control-id="txt_CnsgnrCdLen" />
        <enterkey-order order="6" control-id="txt_CnsgnrCdPst" />
        <enterkey-order order="38" control-id="txt_TCDCFlgReqLen" />
        <enterkey-order order="39" control-id="txt_TCDCFlgReqPst" />
        <enterkey-order order="7" control-id="chk_CommonUseConsignorName" />
        <enterkey-order order="9" control-id="txt_CnsgnrNmLen" />
        <enterkey-order order="10" control-id="txt_CnsgnrNmPst" />
        <enterkey-order order="40" control-id="chk_CommonUseSplCodeAst" />
        <enterkey-order order="41" control-id="txt_SplCdAstLen" />
        <enterkey-order order="42" control-id="txt_SplCdAstPst" />
        <enterkey-order order="11" control-id="txt_CustCdReqLen" />
        <enterkey-order order="12" control-id="txt_CustCdReqPst" />
        <enterkey-order order="43" control-id="chk_CommonUseSplNameAst" />
        <enterkey-order order="44" control-id="txt_SplNmAstLen" />
        <enterkey-order order="45" control-id="txt_SplNmAstPst" />
        <enterkey-order order="13" control-id="chk_CommonUseCustNm" />
        <enterkey-order order="14" control-id="txt_CustNmLen" />
        <enterkey-order order="15" control-id="txt_CustNmPst" />
        <enterkey-order order="46" control-id="chk_CommonUseInstkTktNoAst" />
        <enterkey-order order="47" control-id="txt_InstkTktNoAstLen" />
        <enterkey-order order="48" control-id="txt_InstkTktNoAstPst" />
        <enterkey-order order="16" control-id="txt_TktNoReqLen" />
        <enterkey-order order="17" control-id="txt_TktNoReqPst" />
        <enterkey-order order="49" control-id="chk_CommonUseInstkTktLNoAst" />
        <enterkey-order order="50" control-id="txt_InstkTktLineAstLen" />
        <enterkey-order order="51" control-id="txt_InstkTktLineAstPst" />
        <enterkey-order order="18" control-id="txt_TktLineNoReqLen" />
        <enterkey-order order="19" control-id="txt_TktLineNoReqPst" />
        <enterkey-order order="20" control-id="txt_ItemCdReqLen" />
        <enterkey-order order="21" control-id="txt_ItemCdReqPst" />
        <enterkey-order order="22" control-id="chk_CommonUseBundleItem" />
        <enterkey-order order="23" control-id="txt_BundleItfLength" />
        <enterkey-order order="24" control-id="txt_BundleItfPosition" />
        <enterkey-order order="25" control-id="chk_CommonUseCaseItf" />
        <enterkey-order order="26" control-id="txt_CaseItfLength" />
        <enterkey-order order="27" control-id="txt_CaseItfPosition" />
        <enterkey-order order="28" control-id="chk_CommonUseBundleEntering" />
        <enterkey-order order="29" control-id="txt_BdlEtrLen" />
        <enterkey-order order="30" control-id="txt_BdlEtrPst" />
        <enterkey-order order="31" control-id="txt_CaseEtrReqLen" />
        <enterkey-order order="32" control-id="txt_CaseEtrReqPst" />
      </enterkey-orders>
    </page>
    <page path="/system/loaddata/LoadData" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_PlanDate" />
        <enterkey-order order="4" control-id="chk_InstockPlanData" />
        <enterkey-order order="5" control-id="chk_StoragePlanData" />
        <enterkey-order order="6" control-id="chk_IdmAuto" />
        <enterkey-order order="7" control-id="chk_RetrievalPlanData" />
        <enterkey-order order="8" control-id="chk_PickingPlanData" />
        <enterkey-order order="9" control-id="chk_ShippingPlanData" />
      </enterkey-orders>
    </page>
    <page path="/system/reportdataplan/ReportDataPlan" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_WorkDate1" />
        <enterkey-order order="4" control-id="chk_ComUseSelectInstk" />
        <enterkey-order order="5" control-id="chk_ComUseWorkProgInstk" />
        <enterkey-order order="6" control-id="chk_ComUseRupwiInstk" />
        <enterkey-order order="7" control-id="chk_ComUseSelectStrg" />
        <enterkey-order order="8" control-id="chk_ComUseWorkProgStrg" />
        <enterkey-order order="9" control-id="chk_ComUseRupwiStrg" />
        <enterkey-order order="10" control-id="chk_ComUseSelectRtrivl" />
        <enterkey-order order="11" control-id="chk_ComUseWorkProgRtrivl" />
        <enterkey-order order="12" control-id="chk_ComUseRupwiRtrivl" />
        <enterkey-order order="13" control-id="chk_ComUseSelectPick" />
        <enterkey-order order="14" control-id="chk_ComUseWorkProgPick" />
        <enterkey-order order="15" control-id="chk_ComUseRupwiPick" />
        <enterkey-order order="16" control-id="chk_ComUseSelectShp" />
        <enterkey-order order="17" control-id="chk_ComUseWorkProgShp" />
        <enterkey-order order="18" control-id="chk_ComUseRupwiShp" />
      </enterkey-orders>
    </page>
    <page path="/system/reportdatanoplan/ReportDataNoPlan" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_WorkDate" />
        <enterkey-order order="4" control-id="chk_StockMovRsltData" />
        <enterkey-order order="5" control-id="chk_InvntryRsltData" />
        <enterkey-order order="6" control-id="chk_NoPlanStorageRsltData" />
        <enterkey-order order="7" control-id="chk_NoPlanRetrievalRsltData" />
      </enterkey-orders>
    </page>
    <page path="/system/definereportdata/DefineReportData" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="rdo_ResultInstock" />
        <enterkey-order order="4" control-id="rdo_ResultStorage" />
        <enterkey-order order="5" control-id="rdo_ResultRetrieval" />
        <enterkey-order order="6" control-id="rdo_ResultPicking" />
        <enterkey-order order="7" control-id="rdo_ResultShipping" />
        <enterkey-order order="8" control-id="rdo_ResultStockMove" />
        <enterkey-order order="9" control-id="rdo_ResultInventory" />
        <enterkey-order order="10" control-id="rdo_ResultNoPlanStrg" />
        <enterkey-order order="11" control-id="rdo_ResultNoPlanRtrivl" />
      </enterkey-orders>
    </page>
    <page path="/system/definereportdata/DefineReportDataShipping" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="chk_CommonUseShpPlanDate" />
        <enterkey-order order="2" control-id="txt_ShpPlanDatePst" />
        <enterkey-order order="29" control-id="chk_CommonUseShpPlanPtl" />
        <enterkey-order order="30" control-id="txt_ShpPlanQtyPtlPst" />
        <enterkey-order order="3" control-id="chk_CommonUseOdd" />
        <enterkey-order order="4" control-id="txt_OdrgDatePst" />
        <enterkey-order order="31" control-id="chk_CommonUseTCDC" />
        <enterkey-order order="32" control-id="txt_TCDCFlagPosition" />
        <enterkey-order order="5" control-id="chk_CommonUseCnsgnrCd" />
        <enterkey-order order="6" control-id="txt_CnsgnrCdPst" />
        <enterkey-order order="33" control-id="chk_CommonUseSplCd" />
        <enterkey-order order="34" control-id="txt_SplCdPst" />
        <enterkey-order order="7" control-id="chk_CommonUseCnsgnrNm" />
        <enterkey-order order="8" control-id="txt_CnsgnrNmPst" />
        <enterkey-order order="35" control-id="chk_CommonUseSplNm" />
        <enterkey-order order="36" control-id="txt_SplNmPstNm" />
        <enterkey-order order="9" control-id="chk_CommonUseCustCd" />
        <enterkey-order order="10" control-id="txt_CustCdPst" />
        <enterkey-order order="37" control-id="chk_CommonUseInstkTkt" />
        <enterkey-order order="38" control-id="txt_InstkTktNoPst" />
        <enterkey-order order="11" control-id="chk_CommonUseCustNm" />
        <enterkey-order order="12" control-id="txt_CustNmPst" />
        <enterkey-order order="39" control-id="chk_CommonUseInstkTktLine" />
        <enterkey-order order="40" control-id="txt_InstkTktLineNoPst" />
        <enterkey-order order="13" control-id="chk_CommonUseTktNo" />
        <enterkey-order order="14" control-id="txt_TicketNoPosition" />
        <enterkey-order order="41" control-id="chk_CommonUseShpPtl" />
        <enterkey-order order="42" control-id="txt_ShpQtyPtlPst" />
        <enterkey-order order="15" control-id="chk_CommonUseTktLineNo" />
        <enterkey-order order="16" control-id="txt_TktLineNoPst" />
        <enterkey-order order="43" control-id="chk_CommonUseShpRslt" />
        <enterkey-order order="44" control-id="txt_ShpRsltDatePst" />
        <enterkey-order order="17" control-id="chk_TktLineNoPstItemCo" />
        <enterkey-order order="18" control-id="txt_ItemCodePosition" />
        <enterkey-order order="45" control-id="chk_CommonUseRsltFlg" />
        <enterkey-order order="46" control-id="txt_ResultFlagPosition" />
        <enterkey-order order="19" control-id="chk_CommonUseBdlItf" />
        <enterkey-order order="20" control-id="txt_BundleItfPosition" />
        <enterkey-order order="47" control-id="chk_CommonUseUseByDate" />
        <enterkey-order order="48" control-id="txt_UseByDatePosition" />
        <enterkey-order order="21" control-id="chk_CommonUseCaseItf" />
        <enterkey-order order="22" control-id="txt_CaseItfPosition" />
        <enterkey-order order="23" control-id="chk_CommonUseBdlEtr" />
        <enterkey-order order="24" control-id="txt_BdlEtrPst" />
        <enterkey-order order="25" control-id="chk_CommonUseCaseEtr" />
        <enterkey-order order="26" control-id="txt_CaseEtrPst" />
        <enterkey-order order="27" control-id="chk_W_CommonUseItemNm" />
        <enterkey-order order="28" control-id="txt_ItemNamePosition" />
      </enterkey-orders>
    </page>
    <page path="/system/loaddataenvironment/LoadDataEnvironment" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_InstkPlanFld" />
        <enterkey-order order="4" control-id="txt_InstkPlanFileNm" />
        <enterkey-order order="5" control-id="txt_StrgPlanFld" />
        <enterkey-order order="6" control-id="txt_StrgPlanFileNm" />
        <enterkey-order order="7" control-id="txt_RtrivlPlanFld" />
        <enterkey-order order="8" control-id="txt_RtrivlPlanFileNm" />
        <enterkey-order order="9" control-id="txt_PickPlanFld" />
        <enterkey-order order="10" control-id="txt_PickPlanFileNm" />
        <enterkey-order order="11" control-id="txt_ShpPlanFld" />
        <enterkey-order order="12" control-id="txt_ShpPlanFileNm" />
      </enterkey-orders>
    </page>
    <page path="/system/reportdataenvironment/ReportDataEnvironment" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_InstkRsltFld" />
        <enterkey-order order="4" control-id="txt_InstkRsltFileNm" />
        <enterkey-order order="5" control-id="txt_StrgRsltFld" />
        <enterkey-order order="6" control-id="txt_StrgRsltFileNm" />
        <enterkey-order order="7" control-id="txt_RtrivlRsltFld" />
        <enterkey-order order="8" control-id="txt_RtrivlRsltFileNm" />
        <enterkey-order order="9" control-id="txt_PickRsltFld" />
        <enterkey-order order="10" control-id="txt_PickRsltFileNm" />
        <enterkey-order order="11" control-id="txt_ShpRsltFld" />
        <enterkey-order order="12" control-id="txt_ShpRsltFileNm" />
        <enterkey-order order="13" control-id="txt_StockMovRsltFld" />
        <enterkey-order order="14" control-id="txt_StockMovRsltFileNm" />
        <enterkey-order order="15" control-id="txt_InvntryRsltFld" />
        <enterkey-order order="16" control-id="txt_InvntryRsltFileNm" />
        <enterkey-order order="17" control-id="txt_NoPlanStrgFld" />
        <enterkey-order order="18" control-id="txt_NoPlanStrgFileNm" />
        <enterkey-order order="19" control-id="txt_NoPlanRtrivlFld" />
        <enterkey-order order="20" control-id="txt_NoPlanRtrivlFileNm" />
      </enterkey-orders>
    </page>
    <page path="/system/communication/Communication" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RftMachineNo" />
        <enterkey-order order="2" control-id="txt_SerchStartDate" />
        <enterkey-order order="3" control-id="txt_SearchStartTime" />
        <enterkey-order order="4" control-id="txt_SerchEndDate" />
        <enterkey-order order="5" control-id="txt_SearchEndTime" />
        <enterkey-order order="6" control-id="rdo_DcdAll" />
      </enterkey-orders>
    </page>
    <page path="/system/dailyupdate/DailyUpdate" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_FDate" />
        <enterkey-order order="4" control-id="rdo_Delete" />
      </enterkey-orders>
    </page>
    <page path="/system/message/Message" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_SerchStartDateDate" />
        <enterkey-order order="2" control-id="txt_SearchStartTimeDateTime" />
        <enterkey-order order="3" control-id="txt_SerchEndDateDate" />
        <enterkey-order order="4" control-id="txt_SearchEndTimeDateTime" />
        <enterkey-order order="5" control-id="rdo_DcdAll" />
      </enterkey-orders>
    </page>
    <page path="/system/rftstate/RFTState" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="btn_View" />
      </enterkey-orders>
    </page>
    <page path="/system/registworkermaster/RegistWorkerMaster" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode_T" />
        <enterkey-order order="2" control-id="txt_Password_T" />
        <enterkey-order order="3" control-id="txt_WorkerCode" />
        <enterkey-order order="4" control-id="txt_Name" />
        <enterkey-order order="5" control-id="txt_Furigana" />
        <enterkey-order order="6" control-id="pul_Gender" />
        <enterkey-order order="7" control-id="pul_Jobtype" />
        <enterkey-order order="8" control-id="pul_Access" />
        <enterkey-order order="9" control-id="txt_Password" />
        <enterkey-order order="10" control-id="txt_Memo1" />
        <enterkey-order order="11" control-id="txt_Memo2" />
      </enterkey-orders>
    </page>
    <page path="/system/correctworkermaster/CorrectWorkerMaster" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode_T" />
        <enterkey-order order="2" control-id="txt_Password_T" />
        <enterkey-order order="3" control-id="txt_WorkerCode" />
      </enterkey-orders>
    </page>
    <page path="/system/correctworkermaster/CorrectWorkerMaster2" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_Name" />
        <enterkey-order order="2" control-id="txt_Furigana" />
        <enterkey-order order="3" control-id="pul_Gender" />
        <enterkey-order order="4" control-id="pul_Jobtype" />
        <enterkey-order order="5" control-id="pul_Access" />
        <enterkey-order order="6" control-id="txt_Password" />
        <enterkey-order order="7" control-id="txt_Memo1" />
        <enterkey-order order="8" control-id="txt_Memo2" />
        <enterkey-order order="9" control-id="rdo_UseOn" />
      </enterkey-orders>
    </page>
    <page path="/system/workerqtyinquiry/WorkerQtyInquiry" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_WorkDetails" />
        <enterkey-order order="2" control-id="txt_StartWorkDate" />
        <enterkey-order order="3" control-id="txt_EndWorkDate" />
        <enterkey-order order="4" control-id="txt_WorkerCode" />
        <enterkey-order order="5" control-id="rdo_TermTotal" />
      </enterkey-orders>
    </page>
    <page path="/system/workingdateset/WorkingDateSet" resource-key="">
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_WorkerCode" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_WorkDate1" />