<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE controls[
<!ELEMENT controls (control?)>
<!ELEMENT control (single-data+,datas)>
<!ELEMENT datas (plural-data+)>
<!ELEMENT plural-data (Item*)>
<!ATTLIST control
  id CDATA #REQUIRED
  reflection (true|false) "false">
<!ATTLIST single-data
  name CDATA #REQUIRED
  value CDATA #REQUIRED>
<!ATTLIST item
  value CDATA #REQUIRED>
]>
<controls>
  <control id="lbl_Dynasty" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_ItemNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_ItemNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Search_POPUP" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Help" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="message" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_DateTo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_SettingName" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_DateTimeRange" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Star1" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_ColorCode" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_ToMenu" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_DateFrom" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_DateFrom" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Section" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Star2" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_DateTo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="tab" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_TimeFrom" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_TimeFrom" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Section" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_TimeTo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_TimeTo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_ItemName1" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_ColorCode" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_to" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Line" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Line" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_WhenNextWorkBegin" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_WhenNextWorkBegin" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
</controls>