<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE controls[
<!ELEMENT controls (control?)>
<!ELEMENT control (single-data+,datas)>
<!ELEMENT datas (plural-data+)>
<!ELEMENT plural-data (Item*)>
<!ATTLIST control
  id CDATA #REQUIRED
  reflection (true|false) "false">
<!ATTLIST single-data
  name CDATA #REQUIRED
  value CDATA #REQUIRED>
<!ATTLIST item
  value CDATA #REQUIRED>
]>
<controls>
  <control id="lst_PRStockout" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_SuccessCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Input" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_PRCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_QtyNotMatchCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_NotExistsCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_SelectAll" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_CancelData" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Status" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Status" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_SuccessCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Clear" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_ShortageCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Subdivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_SettingName" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Help" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="message" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="tab" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_ToMenu" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_PRNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_PRNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_RetrievaledCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_UnselectAll" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_NotExistsCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Set" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_ShortageCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="pul_Subdivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_RetrievaledCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_QtyNotMatchCount" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
</controls>