<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE controls[
<!ELEMENT controls (control?)>
<!ELEMENT control (single-data+,datas)>
<!ELEMENT datas (plural-data+)>
<!ELEMENT plural-data (Item*)>
<!ATTLIST control
  id CDATA #REQUIRED
  reflection (true|false) "false">
<!ATTLIST single-data
  name CDATA #REQUIRED
  value CDATA #REQUIRED>
<!ATTLIST item
  value CDATA #REQUIRED>
]>
<controls>
  <control id="message" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_ToMenu" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_OtherProcedure" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Section" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Section2" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Section3" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_WhenNextWorkBegin" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_UnselectAll" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Show" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="pul_Subdivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="chk_DisplayFinishedRetrieval" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_LineDivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_RetrievalNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Delete" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_AssemblyLineWorkingProcedu" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_WhenThisWorkFinishInPlan" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="pgr_Low" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_OrderBy" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="pgr_Up" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_WhenNextWorkBegin" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_SelectAll" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_ShowShortageCondition" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_FinalProcedure" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Subdivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_StockOutDeletionPassword" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_LineDivision" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_ItemNo" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Set_Low" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Line" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="rdo_WhenNextWorkBegin" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lst_Stockout" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="pul_AmPm" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="btn_Set_Up" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="txt_Section4" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_Line" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
  <control id="lbl_SettingName" reflection="false">
    <single-data name="text" value="" />
    <single-data name="maxrows" value="" />
    <datas>
      <plural-data />
    </datas>
  </control>
</controls>